INSERT INTO questions (text, dimension, weight) VALUES
-- Ekonomska pitanja (economic)
('Država treba da kontroliše cene osnovnih životnih namirnica', 'economic', 1.5),
('Privatizacija državnih preduzeća je dobra stvar', 'economic', 1.0),
('Država treba da osigura besplatno zdravstvo za sve građane', 'economic', 1.5),
('Porezi za bogate treba da budu veći', 'economic', 1.0),
('Država treba da kontroliše banke', 'economic', 1.0),
('Minimalna zarada treba da bude veća', 'economic', 1.0),
('Država treba da subvencioniše poljoprivredu', 'economic', 1.0),
('Penzije treba da budu veće', 'economic', 1.0),
('Država treba da kontroliše cene stanova', 'economic', 1.0),
('Privatni sektor je efikasniji od državnog', 'economic', 1.0),

-- Socijalna pitanja (social)
('Država treba da kontroliše medije', 'social', 1.5),
('Država treba da kontroliše internet', 'social', 1.0),
('Država treba da kontroliše obrazovanje', 'social', 1.0),
('Država treba da kontroliše verske zajednice', 'social', 1.0),
('Država treba da kontroliše sindikate', 'social', 1.0),
('Država treba da kontroliše nevladine organizacije', 'social', 1.0),
('Država treba da kontroliše javne skupove', 'social', 1.0),
('Država treba da kontroliše stranke', 'social', 1.0),
('Država treba da kontroliše sudstvo', 'social', 1.0),
('Država treba da kontroliše policiju', 'social', 1.0),

-- Nacionalistička pitanja (nationalism)
('Srbija treba da postane članica EU', 'nationalism', 1.5),
('Srbija treba da se približi Rusiji', 'nationalism', 1.0),
('Srbija treba da prizna Kosovo', 'nationalism', 1.5),
('Srbija treba da se distancira od Zapada', 'nationalism', 1.0),
('Srbija treba da se distancira od Istoka', 'nationalism', 1.0),
('Srbija treba da bude neutralna', 'nationalism', 1.0),
('Srbija treba da se približi Kini', 'nationalism', 1.0),
('Srbija treba da se približi SAD', 'nationalism', 1.0),
('Srbija treba da se približi Rusiji i Kini', 'nationalism', 1.0),
('Srbija treba da se približi EU i SAD', 'nationalism', 1.0),

-- Tradicionalistička pitanja (traditionalism)
('Država treba da zaštiti tradicionalne vrednosti', 'traditionalism', 1.5),
('Država treba da zaštiti verske vrednosti', 'traditionalism', 1.0),
('Država treba da zaštiti porodične vrednosti', 'traditionalism', 1.0),
('Država treba da zaštiti LGBT prava', 'traditionalism', 1.5),
('Država treba da zaštiti prava žena', 'traditionalism', 1.0),
('Država treba da zaštiti prava dece', 'traditionalism', 1.0),
('Država treba da zaštiti prava starih', 'traditionalism', 1.0),
('Država treba da zaštiti prava invalida', 'traditionalism', 1.0),
('Država treba da zaštiti prava manjina', 'traditionalism', 1.0),
('Država treba da zaštiti prava većine', 'traditionalism', 1.0),

-- Regionalna pitanja (regionalism)
('Vojvodina treba da ima više autonomije', 'regionalism', 1.5),
('Srbija treba da bude centralizovana država', 'regionalism', 1.0),
('Regioni treba da imaju više vlasti', 'regionalism', 1.0),
('Gradovi treba da imaju više vlasti', 'regionalism', 1.0),
('Opštine treba da imaju više vlasti', 'regionalism', 1.0),
('Država treba da kontroliše sve nivoe vlasti', 'regionalism', 1.0),
('Država treba da kontroliše lokalne izbore', 'regionalism', 1.0),
('Država treba da kontroliše lokalne budžete', 'regionalism', 1.0),
('Država treba da kontroliše lokalne medije', 'regionalism', 1.0),
('Država treba da kontroliše lokalnu policiju', 'regionalism', 1.0); 